[[ISSUERS]]
address = "r971HKTQemg2cKoTTbHrDsV2Ty6S9K1T8j"
name = „DavidSchwartz.meme” 

[[TOKENS]]
issuer = "r971HKTQemg2cKoTTbHrDsV2Ty6S9K1T8j"
currency = „DAVID”
name = „DavidSchwartz”
desc = „DavidSchwartz (DAVID) is a memecoin” 
icon = xxx

[[TOKENS.WEBLINKS]]
url = "https://davidschwartz.meme”
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://twitter.com/JoelKatzTheMeme"
type = "socialmedia"